### ISSUE TITLE
Add IPFS and swarm deploy scripts.

### ISSUE THREAD

**Issue by AugustoL** [levelkdev/dxtrust#213]
Add scirpts to deploy to IPFS and swarm with instructions in readme.

**Comment by Phinneas** [comment]
I think I'd like to work this one.

**Comment by pimato** [comment]
> I think I'd like to work this one.
> By swarm I assume you mean Docker swarm deployment.

Ethereum has build a competitor to IPFS, check it out here:
https://swarm.ethereum.org/

**Comment by AugustoL** [comment]
@Phinneas We mean ipfs.io and https://swarm-gateways.net/, we have a scripts folder with shell scritps. The idea would be to have shells scripts that upload the build folder to that networks.
